# Objective

The objective of this program is to extract and visualize information of the dataset.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [3]:
visual_df = pd.read_csv('Visualization Dataset.csv')

In [5]:
visual_df.head(5)

,Unnamed: 0,Product Name,Discounted Price,Original Price,Warranty,Stock Status,4k,Smart,LED,Full HD,...,QLED,HDR,PRO,Slim,Curved,8k,Theatre,Dynamic Range,Screen Size,Ultra-HD
0,0,Philips 32PHT4002/98 32-inch 4000 Series Slim ...,699,799,2,In stock,0,0,1,0,...,0,0,0,1,0,0,0,0,32,0
1,1,Toshiba 43-inch Smart LED TV,1399,1645,2,In stock,0,1,1,0,...,0,0,0,0,0,0,0,0,43,0
2,2,Sony 32-inch LED TV,989,1036,2,In stock,0,0,1,0,...,0,0,0,0,0,0,0,0,32,0
3,3,Sony 40-inch Full HD LED TV,1299,1444,2,In stock,0,0,1,1,...,0,0,0,0,0,0,0,0,40,0
4,4,Toshiba 49-inch Full HD LED TV,1499,2299,2,In stock,0,0,1,1,...,0,0,0,0,0,0,0,0,49,0

In [6]:
visual_df.describe()

,Unnamed: 0,Discounted Price,Original Price,Warranty,4k,Smart,LED,Full HD,Android,OLED,QLED,HDR,PRO,Slim,Curved,8k,Theatre,Dynamic Range,Screen Size,Ultra-HD
count,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000
mean,51.000000,4889.718447,5880.106796,1.990291,0.533981,0.407767,0.495146,0.145631,0.126214,0.048544,0.087379,0.067961,0.048544,0.048544,0.019417,0.019417,0.019417,0.019417,53.601942,0.621359
std,29.877528,6059.633706,6623.972218,0.408132,0.501283,0.493822,0.502421,0.354461,0.333714,0.215963,0.283770,0.252910,0.215963,0.215963,0.138662,0.138662,0.138662,0.138662,13.055192,0.487420
min,0.000000,399.000000,439.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.000000,0.000000
25%,25.500000,1399.500000,1809.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,43.000000,0.000000
50%,51.000000,2499.000000,3099.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,55.000000,1.000000
75%,76.500000,5999.000000,7279.000000,2.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,65.000000,1.000000
max,102.000000,35999.000000,36999.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,85.000000,1.000000

In [32]:
'''
The Most Expensive TV
'''
print(visual_df.iloc[visual_df['Original Price'].idxmax()])
print('\n')
print(visual_df.iloc[visual_df['Discounted Price'].idxmax()])

Unnamed: 0                                 66
Product Name           Sharp 8K Resolution TV
Discounted Price                        35999
Original Price                          36999
Warranty                                    2
Stock Status                         In stock
4k                                          0
Smart                                       0
LED                                         0
Full HD                                     0
Android                                     0
OLED                                        0
QLED                                        0
HDR                                         0
PRO                                         0
Slim                                        0
Curved                                      0
8k                                          1
Theatre                                     0
Dynamic Range                               0
Screen Size                                70
Ultra-HD                                    0
Discount Value                           1000
Discount Percentage                   2.70278
Name: 66, dtype: object


Unnamed: 0                                 66
Product Name           Sharp 8K Resolution TV
Discounted Price                        35999
Original Price                          36999
Warranty                                    2
Stock Status                         In stock
4k                                          0
Smart                                       0
LED                                         0
Full HD                                     0
Android                                     0
OLED                                        0
QLED                                        0
HDR                                         0
PRO                                         0
Slim                                        0
Curved                                      0
8k                                          1
Theatre                                     0
Dynamic Range                               0
Screen Size                                70
Ultra-HD                                    0
Discount Value                           1000
Discount Percentage                   2.70278
Name: 66, dtype: object

In [33]:
'''
The Cheapest TV
'''
print(visual_df.iloc[visual_df['Original Price'].idxmin()])
print('\n')
print(visual_df.iloc[visual_df['Discounted Price'].idxmin()])

Unnamed: 0                                  12
Product Name           Pensonic 24-inch LED TV
Discounted Price                           399
Original Price                             439
Warranty                                     2
Stock Status                          In stock
4k                                           0
Smart                                        0
LED                                          1
Full HD                                      0
Android                                      0
OLED                                         0
QLED                                         0
HDR                                          0
PRO                                          0
Slim                                         0
Curved                                       0
8k                                           0
Theatre                                      0
Dynamic Range                                0
Screen Size                                 24
Ultra-HD                                     0
Discount Value                              40
Discount Percentage                    9.11162
Name: 12, dtype: object


Unnamed: 0                                  12
Product Name           Pensonic 24-inch LED TV
Discounted Price                           399
Original Price                             439
Warranty                                     2
Stock Status                          In stock
4k                                           0
Smart                                        0
LED                                          1
Full HD                                      0
Android                                      0
OLED                                         0
QLED                                         0
HDR                                          0
PRO                                          0
Slim                                         0
Curved                                       0
8k                                           0
Theatre                                      0
Dynamic Range                                0
Screen Size                                 24
Ultra-HD                                     0
Discount Value                              40
Discount Percentage                    9.11162
Name: 12, dtype: object

In [34]:
visual_df['Discount Value'] = visual_df['Original Price'] - visual_df['Discounted Price']

In [35]:
'''
Highest Discount Value
'''
print(visual_df.iloc[visual_df['Discount Value'].idxmax()])

Unnamed: 0                                          81
Product Name           Skyworth 75-Inch Android UHD TV
Discounted Price                                  7299
Original Price                                   15999
Warranty                                             2
Stock Status                                  In stock
4k                                                   0
Smart                                                0
LED                                                  0
Full HD                                              0
Android                                              1
OLED                                                 0
QLED                                                 0
HDR                                                  0
PRO                                                  0
Slim                                                 0
Curved                                               0
8k                                                   0
Theatre                                              0
Dynamic Range                                        0
Screen Size                                         75
Ultra-HD                                             1
Discount Value                                    8700
Discount Percentage                            54.3784
Name: 81, dtype: object

In [36]:
'''
Lowest Discount Value
'''
print(visual_df.iloc[visual_df['Discount Value'].idxmin()])

Unnamed: 0                                                            61
Product Name           MSI 27-Inch Curved Gaming Monitor Optix MAG27C...
Discounted Price                                                    1400
Original Price                                                      1400
Warranty                                                               2
Stock Status                                                    In stock
4k                                                                     0
Smart                                                                  0
LED                                                                    0
Full HD                                                                0
Android                                                                0
OLED                                                                   0
QLED                                                                   0
HDR                                                                    0
PRO                                                                    0
Slim                                                                   0
Curved                                                                 1
8k                                                                     0
Theatre                                                                0
Dynamic Range                                                          0
Screen Size                                                           27
Ultra-HD                                                               0
Discount Value                                                         0
Discount Percentage                                                    0
Name: 61, dtype: object

In [37]:
visual_df['Discount Percentage'] = visual_df['Discount Value'] / visual_df['Original Price'] *100

In [38]:
'''
Higest Discount Percentage
'''
visual_df.iloc[visual_df['Discount Percentage'].idxmax()]

Unnamed: 0                                          81
Product Name           Skyworth 75-Inch Android UHD TV
Discounted Price                                  7299
Original Price                                   15999
Warranty                                             2
Stock Status                                  In stock
4k                                                   0
Smart                                                0
LED                                                  0
Full HD                                              0
Android                                              1
OLED                                                 0
QLED                                                 0
HDR                                                  0
PRO                                                  0
Slim                                                 0
Curved                                               0
8k                                                   0
Theatre                                              0
Dynamic Range                                        0
Screen Size                                         75
Ultra-HD                                             1
Discount Value                                    8700
Discount Percentage                            54.3784
Name: 81, dtype: object

In [39]:
'''
Lowest Discount Percentage
'''
visual_df.iloc[visual_df['Discount Percentage'].idxmin()]

Unnamed: 0                                                            61
Product Name           MSI 27-Inch Curved Gaming Monitor Optix MAG27C...
Discounted Price                                                    1400
Original Price                                                      1400
Warranty                                                               2
Stock Status                                                    In stock
4k                                                                     0
Smart                                                                  0
LED                                                                    0
Full HD                                                                0
Android                                                                0
OLED                                                                   0
QLED                                                                   0
HDR                                                                    0
PRO                                                                    0
Slim                                                                   0
Curved                                                                 1
8k                                                                     0
Theatre                                                                0
Dynamic Range                                                          0
Screen Size                                                           27
Ultra-HD                                                               0
Discount Value                                                         0
Discount Percentage                                                    0
Name: 61, dtype: object

In [44]:
'''
Products that are out of stock
'''
visual_df[visual_df['Stock Status']=='Out of stock']

,Unnamed: 0,Product Name,Discounted Price,Original Price,Warranty,Stock Status,4k,Smart,LED,Full HD,...,PRO,Slim,Curved,8k,Theatre,Dynamic Range,Screen Size,Ultra-HD,Discount Value,Discount Percentage
46,46,Haier 50-inch 4K Ultra HD Smart LED TV,1885,2829,2,Out of stock,1,1,1,0,...,0,0,0,0,0,0,50,1,944,33.368682
51,51,Haier 32-Inch Full HD LED TV,749,889,2,Out of stock,0,0,1,1,...,0,0,0,0,0,0,32,0,140,15.748031
52,52,Sharp 40-Inch Full HD LED TV,899,1349,2,Out of stock,0,0,1,1,...,0,0,0,0,0,0,40,0,450,33.358043
53,53,Sony 75-Inch X85F LED 4K Ultra HDR Android TV,8999,9799,0,Out of stock,1,0,1,0,...,0,0,0,0,0,0,75,1,800,8.164098
54,54,LG 75-Inch Smart 4K Ultra HD TV,7999,12999,0,Out of stock,1,1,0,0,...,0,0,0,0,0,0,75,1,5000,38.464497
73,73,Hisense Smart LED TV,1099,1399,2,Out of stock,0,1,1,0,...,0,0,0,0,0,0,49,0,300,21.443888
74,74,Samsung 55-Inch Q75R QLED 4K UHD TV,7799,7999,2,Out of stock,1,0,1,0,...,0,0,0,0,0,0,55,1,200,2.500313
75,75,Samsung 65-Inch Q75R QLED 4K UHD TV,13599,13999,2,Out of stock,1,0,1,0,...,0,0,0,0,0,0,65,1,400,2.857347
76,76,Samsung 75-Inch Q90R QLED 4K UHD TV,28999,29999,2,Out of stock,1,0,1,0,...,0,0,0,0,0,0,75,1,1000,3.333444
85,85,Skyworth 43-Inch LED TV,1099,1319,2,Out of stock,0,0,1,0,...,0,0,0,0,0,0,43,0,220,16.679303
87,87,Skyworth 32-Inch Smart LED TV,959,1149,2,Out of stock,0,1,1,0,...,0,0,0,0,0,0,32,0,190,16.536118

In [54]:
'''
Products that has no warranty
'''
visual_df['Product Name'][visual_df['Warranty']==0]

53    Sony 75-Inch X85F LED 4K Ultra HDR Android TV
54                  LG 75-Inch Smart 4K Ultra HD TV
57                           Hisense 55-Inch UHD TV
Name: Product Name, dtype: object

In [56]:
'''
Products that has 3 years warranty
'''
visual_df['Product Name'][visual_df['Warranty']==3]

47                 Hisense 55-inch 4K Ultra HD Smart TV
48                      Hisense 49-Inch HD LED Smart TV
56                               Hisense 65-Inch UHD TV
62    Hisense 50-Inch 4K UHD â€“ A6100 - 50A6100UW | S...
63    Hisense 50-Inch 4K UHD â€“ A6501 - 50A6501UW | S...
Name: Product Name, dtype: object